import type { Candidate } from "./types";

/**
 * Seeded candidate network. In production these would be real users whose
 * agents negotiate over the wire; here they power the simulated agent mesh.
 */
export const CANDIDATES: Candidate[] = [
  {
    id: "c1",
    name: "Elena Marsh",
    age: 31,
    city: "Austin",
    headline: "Product designer who cooks her way through every city she visits",
    intents: ["dating", "friendship", "hobbies"],
    agentName: "Aria",
    interests: ["cooking", "hiking", "design", "live music", "travel", "photography"],
    values: ["honesty", "curiosity", "family", "growth"],
    goals: ["long-term relationship", "buy a home", "start a supper club"],
    lifestyle: ["early riser", "active weekends", "rarely drinks", "dog person"],
    dealbreakers: ["smoking", "dishonesty"],
    professional: "Senior product designer at a healthtech startup",
    personality: "Warm, observant, dry sense of humor",
    verified: true,
    privateNote: "Wants children within five years — shares only after trust is built.",
  },
  {
    id: "c2",
    name: "Marcus Chen",
    age: 34,
    city: "Austin",
    headline: "Two-time founder, now angel investing in climate and health",
    intents: ["business", "events"],
    agentName: "Vector",
    interests: ["startups", "climbing", "chess", "climate tech", "reading"],
    values: ["integrity", "ambition", "directness", "craftsmanship"],
    goals: ["invest in 10 seed startups", "mentor first-time founders"],
    lifestyle: ["early riser", "travels monthly", "gym daily"],
    dealbreakers: ["dishonesty", "hype without substance"],
    professional: "Exited B2B SaaS founder; angel investor, $25–100k checks",
    personality: "Direct, generous with time, allergic to buzzwords",
    verified: true,
    privateNote: "Quietly raising a $10M fund — discusses only after mutual interest.",
  },
  {
    id: "c3",
    name: "Priya Raman",
    age: 29,
    city: "Austin",
    headline: "ML engineer, marathoner, and unapologetic sci-fi nerd",
    intents: ["dating", "hobbies", "friendship"],
    agentName: "Nova",
    interests: ["running", "sci-fi", "machine learning", "board games", "coffee", "travel"],
    values: ["curiosity", "kindness", "independence", "growth"],
    goals: ["run all six majors", "long-term relationship", "publish research"],
    lifestyle: ["early riser", "active weekends", "vegetarian", "cat person"],
    dealbreakers: ["smoking", "closed-mindedness"],
    professional: "ML engineer at an autonomy company",
    personality: "Playful, analytical, fiercely loyal",
    verified: true,
    privateNote: "Relocating to Seattle in two years is possible — mentions after several dates.",
  },
  {
    id: "c4",
    name: "Jonah Reyes",
    age: 38,
    city: "Dallas",
    headline: "Restaurateur building a hospitality group, looking for operating partners",
    intents: ["business", "events"],
    agentName: "Compass",
    interests: ["food", "wine", "real estate", "jazz", "golf"],
    values: ["loyalty", "craftsmanship", "family", "hustle"],
    goals: ["open three new locations", "find a COO-level partner"],
    lifestyle: ["night owl", "works weekends", "social drinker"],
    dealbreakers: ["flakiness", "short-term thinking"],
    professional: "Owner of two award-winning restaurants; raising expansion capital",
    personality: "Big-hearted, decisive, old-school about handshakes",
    verified: false,
    privateNote: "Margins on location two are thin — discloses to serious partners only.",
  },
  {
    id: "c5",
    name: "Sofia Andersson",
    age: 27,
    city: "Austin",
    headline: "Indie game developer who hosts a monthly board-game night",
    intents: ["friendship", "hobbies", "events"],
    agentName: "Pixel",
    interests: ["gaming", "board games", "illustration", "anime", "climbing", "coffee"],
    values: ["creativity", "kindness", "community", "humor"],
    goals: ["ship my first commercial game", "grow the game night to 30 regulars"],
    lifestyle: ["night owl", "remote worker", "rarely drinks"],
    dealbreakers: ["negativity", "gatekeeping"],
    professional: "Solo indie developer, ex-studio animator",
    personality: "Goofy, generous, quietly ambitious",
    verified: true,
    privateNote: "Recently moved cities and rebuilding her social circle from scratch.",
  },
  {
    id: "c6",
    name: "David Okafor",
    age: 42,
    city: "Houston",
    headline: "Energy exec turned startup mentor; weekend golfer, lifelong reader",
    intents: ["business", "hobbies", "events"],
    agentName: "Meridian",
    interests: ["golf", "reading", "energy markets", "mentoring", "wine"],
    values: ["integrity", "patience", "excellence", "family"],
    goals: ["mentor five founders a year", "break 80 on the course"],
    lifestyle: ["early riser", "family weekends", "social drinker"],
    dealbreakers: ["arrogance", "cutting corners"],
    professional: "Former VP at an energy major; advises seed-stage energy startups",
    personality: "Measured, wise, unexpectedly funny",
    verified: true,
    privateNote: "Considering a fractional-CFO role — only tells committed founders.",
  },
  {
    id: "c7",
    name: "Isabelle Fontaine",
    age: 33,
    city: "Austin",
    headline: "Pastry chef and salsa dancer who plans trips around bakeries",
    intents: ["dating", "hobbies"],
    agentName: "Saffron",
    interests: ["baking", "dancing", "travel", "languages", "film", "cooking"],
    values: ["passion", "honesty", "spontaneity", "family"],
    goals: ["open a patisserie", "long-term relationship", "learn Portuguese"],
    lifestyle: ["early riser", "active weekends", "social drinker", "dog person"],
    dealbreakers: ["smoking", "jealousy"],
    professional: "Head pastry chef at a boutique hotel",
    personality: "Vibrant, affectionate, stubborn about croissants",
    verified: true,
    privateNote: "Divorced two years ago — prefers to share her story in person.",
  },
  {
    id: "c8",
    name: "Tomás Herrera",
    age: 30,
    city: "Austin",
    headline: "Fintech PM training for his first Ironman",
    intents: ["hobbies", "friendship", "dating"],
    agentName: "Bolt",
    interests: ["triathlon", "running", "cycling", "cooking", "podcasts", "travel"],
    values: ["discipline", "optimism", "growth", "honesty"],
    goals: ["finish an Ironman", "make VP by 33", "find a training crew"],
    lifestyle: ["early riser", "meal preps", "rarely drinks", "active weekends"],
    dealbreakers: ["negativity", "smoking"],
    professional: "Senior PM at a payments company",
    personality: "Upbeat, structured, competitive in a friendly way",
    verified: true,
    privateNote: "Recovering from a knee injury — cautious about high-mileage partners for now.",
  },
  {
    id: "c9",
    name: "Grace Liu",
    age: 36,
    city: "Austin",
    headline: "Ex-McKinsey operator seeking a technical co-founder in health AI",
    intents: ["business", "events"],
    agentName: "Atlas",
    interests: ["health tech", "machine learning", "yoga", "reading", "startups"],
    values: ["excellence", "empathy", "ambition", "integrity"],
    goals: ["find a technical co-founder", "raise a pre-seed by Q2"],
    lifestyle: ["early riser", "yoga daily", "rarely drinks"],
    dealbreakers: ["ego", "low commitment"],
    professional: "Ex-McKinsey EM; 8 years in provider operations; solo founder",
    personality: "Sharp, warm, relentlessly organized",
    verified: true,
    privateNote: "Has a signed LOI with a hospital network — reveals under NDA-level trust.",
  },
  {
    id: "c10",
    name: "Ben Whitfield",
    age: 45,
    city: "San Antonio",
    headline: "Community organizer building the city's largest book club",
    intents: ["friendship", "events", "hobbies"],
    agentName: "Chapter",
    interests: ["reading", "history", "hiking", "chess", "volunteering"],
    values: ["community", "curiosity", "kindness", "patience"],
    goals: ["grow the book club past 500 members", "write a novel"],
    lifestyle: ["early riser", "family weekends", "rarely drinks"],
    dealbreakers: ["cruelty", "chronic lateness"],
    professional: "High-school history teacher and community organizer",
    personality: "Steady, welcoming, encyclopedic about the Civil War",
    verified: true,
    privateNote: "Introvert who needs recovery days — paces his social calendar carefully.",
  },
  {
    id: "c11",
    name: "Nadia Petrov",
    age: 28,
    city: "Austin",
    headline: "Growth marketer and amateur DJ who knows every venue in town",
    intents: ["events", "friendship", "business"],
    agentName: "Tempo",
    interests: ["music", "djing", "marketing", "nightlife", "photography", "travel"],
    values: ["energy", "creativity", "loyalty", "hustle"],
    goals: ["throw a 500-person event", "start a creative agency"],
    lifestyle: ["night owl", "social drinker", "spontaneous trips"],
    dealbreakers: ["flakiness", "snobbery"],
    professional: "Head of growth at a consumer app; freelance event producer",
    personality: "Magnetic, fast-talking, secretly a great listener",
    verified: false,
    privateNote: "Burned by a former business partner — vets collaborators slowly.",
  },
  {
    id: "c12",
    name: "Sam Kessler",
    age: 39,
    city: "Austin",
    headline: "Staff engineer, weekend woodworker, girl-dad of two",
    intents: ["friendship", "hobbies"],
    agentName: "Timber",
    interests: ["woodworking", "hiking", "bbq", "engineering", "camping"],
    values: ["family", "craftsmanship", "honesty", "patience"],
    goals: ["build a canoe from scratch", "find a regular hiking crew"],
    lifestyle: ["early riser", "family weekends", "rarely drinks", "dog person"],
    dealbreakers: ["drama", "one-upmanship"],
    professional: "Staff engineer at a developer-tools company",
    personality: "Calm, dependable, deadpan funny",
    verified: true,
    privateNote: "Limited free time — one weekend slot per month for new friendships.",
  },
];

export const INTEREST_POOL = [
  "cooking", "hiking", "running", "travel", "photography", "reading", "gaming",
  "board games", "live music", "film", "yoga", "climbing", "golf", "cycling",
  "coffee", "wine", "dancing", "startups", "machine learning", "design",
  "volunteering", "podcasts", "sci-fi", "bbq", "camping", "chess", "languages",
];

export const VALUE_POOL = [
  "honesty", "curiosity", "family", "growth", "ambition", "kindness",
  "creativity", "community", "integrity", "loyalty", "discipline",
  "spontaneity", "craftsmanship", "empathy", "humor", "independence",
];

export const LIFESTYLE_POOL = [
  "early riser", "night owl", "active weekends", "rarely drinks",
  "social drinker", "dog person", "cat person", "vegetarian",
  "remote worker", "travels monthly", "meal preps", "family weekends",
];

export const DEALBREAKER_POOL = [
  "smoking", "dishonesty", "negativity", "flakiness", "closed-mindedness",
  "jealousy", "arrogance", "drama", "cruelty", "ego",
];

export const AGENT_NAMES = ["Sage", "Echo", "Lumen", "Orbit", "Quill", "Ember", "Halo", "Cipher"];
